import { Resend } from "resend";
import { NextResponse } from "next/server";

export const dynamic = "force-dynamic";

/**
 * POST /api/send-email
 *
 * Body: { title: string; description: string; to?: string | string[] }
 *
 * Sends a tactical alert email via Resend. The recipient is taken from
 * `to` in the payload, falling back to the ALERT_EMAIL_TO env var, so
 * there are no hardcoded addresses in source.
 */
export async function POST(request: Request) {
  try {
    if (!process.env.RESEND_API_KEY) {
      return NextResponse.json(
        { error: "Email service not configured" },
        { status: 500 }
      );
    }

    const resend = new Resend(process.env.RESEND_API_KEY);
    const { title, description, to } = await request.json();

    const recipients =
      (Array.isArray(to) ? to : typeof to === "string" ? [to] : undefined) ??
      (process.env.ALERT_EMAIL_TO
        ? process.env.ALERT_EMAIL_TO.split(",").map((s) => s.trim()).filter(Boolean)
        : undefined);

    if (!recipients || recipients.length === 0) {
      return NextResponse.json(
        { error: "No alert recipient configured (set ALERT_EMAIL_TO)" },
        { status: 500 }
      );
    }

    const fromAddress =
      process.env.ALERT_EMAIL_FROM ?? "DECK/01 <onboarding@resend.dev>";

    const { data, error } = await resend.emails.send({
      from: fromAddress,
      to: recipients,
      subject: `[ALERT] ${title}`,
      html: `
        <h2>${title}</h2>
        <p>${description}</p>
        <p><em>Generated by DECK/01 real-time monitoring.</em></p>
      `,
    });

    if (error) {
      console.error("Resend API error:", error);
      return NextResponse.json({ error });
    }

    return NextResponse.json({ data });
  } catch (error) {
    console.error("send-email error:", error);
    return NextResponse.json({
      error: error instanceof Error ? error.message : "Unknown error",
    });
  }
}
